### PR TITLE
fix(entities): typed support for immutable/readonly arrays

### PR DESCRIPTION
**Pull request by mdudek**
fix(entities): code cleanup

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by mdudek** [comment]
Thanks for merging. I found that you published v2 version of @ngneat/elf-entities to npm, but new version of @ngneat/elf was not published  yet. Can I expect it soon ?

**Comment by NetanelBasal** [comment]
done

**Comment by fwestberg** [comment]
Following the merge of this PR, I'm experiencing type errors:

Screenshot 2021-12-14 at 12 38 28

The above example can be reproduced by updating the dependencies in [the Angular Books example on StackBlitz.](https://stackblitz.com/edit/angular-ivy-ukapsm?file=src/app/state/books.repository.ts)

Is this intentional? And if so, what's the best way to go about it (without using union types)?

**Comment by NetanelBasal** [comment]
@mdudek, this change wasn't supposed to create a breaking change. Please check, and if that's the case, I'm reverting this.

**Comment by NetanelBasal** [comment]
It forces to use `@Input() books: ReadonlyArray<Book>`

**Comment by mdudek** [comment]
I checked that, you are right, this change require to declare bound properties as ReadonlyArray. I didn't found this issue, because I'm using immutable types everywhere in my projects. 

I don't see perfect solution at this moment. Usage of ReadonlyArray type in code prevents to write modification code, on the other side it breaks usage of Array type in projects, that does not use immutability.

We can create 'readonly versions' of all queries & mutations, but its not a pretty solution.

**Comment by NetanelBasal** [comment]
Can you please first revert the change? We'll think about it afterward.

**Comment by mdudek** [comment]
ok, what is a right way to revert pull request?  If it helps I can create new commit with reverted changes.

**Comment by NetanelBasal** [comment]
Sure

**Comment by mdudek** [comment]
Commited

**Comment by NetanelBasal** [comment]
PR

**Comment by NetanelBasal** [comment]
Thanks. @fwestberg should be ok now.

**Pull request merged**
