### PR TITLE
feat(devtools): add option for log trace

### PR DESCRIPTION
**Pull request by arvidOtt**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #296

## What is the new behavior?

Add log trace option to dev tools

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by arvidOtt** [comment]
@NetanelBasal could you review this?

**Comment by NetanelBasal** [comment]
Fix lint, please

**Comment by arvidOtt** [comment]
@NetanelBasal sorry for that. Should be fine now.
` >  NX   Successfully ran target lint for project devtools (11ms)`

**Comment by arvidOtt** [comment]
@NetanelBasal would you run it another time?

**Pull request merged**
