### PR TITLE
docs: fixes incorrect number of parameters in `withRequestsCache`

### PR DESCRIPTION
**Pull request by pavankjadda**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
according to docs, `withRequestsCache` accepts two parameters like `withRequestsCache<'todos','todo-${string}'>()`, while the API accepts only one parameter.

Issue Number: N/A

## What is the new behavior?
This PR updates the docs to sync with API.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
Why it's incorrect?

**Comment by bifty** [comment]
Docs say
`withRequestsCache<`todos`, `todo-${string}`>()`

Code says
`withRequestsCache<Keys extends string>()`

**Comment by NetanelBasal** [comment]
It should be `<'todos' | 'todo-${string}'>`

**Comment by pavankjadda** [comment]
> It should be `<'todos' | 'todo-${string}'>`

Correct. Updated it

**Pull request merged**
