### PR TITLE
Added function getManyByPredicate

### PR DESCRIPTION
**Pull request by Sir-J**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the new behavior?

Added function getManyByPredicate

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by Sir-J** [comment]
Strange error in build process: 

    Error during bundle: Error: 'StoreConfig' is not exported by packages/store/src/lib/create-store.ts, imported by packages/store/src/index.ts

**Comment by NetanelBasal** [comment]
I'll check

**Comment by Sir-J** [comment]
@NetanelBasal so, i pulled master, but right now, build fail on package install stage. Your last master build failed to

**Comment by NetanelBasal** [comment]
Run npm i with legacy

**Comment by Sir-J** [comment]
It wasn't help me. Locally install without problem

**Comment by hakimio** [comment]
@NetanelBasal this might help resolve the install issue on github actions: https://github.com/nrwl/nx/issues/17767#issuecomment-1630543307

**Comment by NetanelBasal** [comment]
Tests are failing @Sir-J 

Screenshot 2023-09-24 at 10 44 18

**Comment by NetanelBasal** [comment]
https://github.com/ngneat/elf/actions/runs/6288823321/job/17074674317

**Comment by Sir-J** [comment]
> https://github.com/ngneat/elf/actions/runs/6288823321/job/17074674317
Just a moment ...

**Comment by Sir-J** [comment]
Fixed. Created new new request

**Pull request merged**
