### PR TITLE
feat(store): add  setPropsInitialValue to have ability update initial value passed to propsFactory

### PR DESCRIPTION
**Pull request by EricPoul**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngneat/elf/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: https://github.com/ngneat/elf/issues/274

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by NetanelBasal** [comment]
I didn't mean to make a breaking change. I thought it was an addition to the current API.

**Comment by EricPoul** [comment]
@NetanelBasal one breaking change is that I removed an argument from `withProps` because it's not needed and can only confuse(like before)

**Comment by NetanelBasal** [comment]
I prefer to leave it as is and add this additional function.

**Comment by EricPoul** [comment]
Ok, I'll bring it back

**Pull request merged**
